name: npm publish

on:
  push:
    tags:
      - 'v*'

jobs:
  npm_publish:
    permissions:
      contents: write # Allows this job to create releases

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Install deps and build
        run: |
          pnpm install
          pnpm build

      - name: Publish package
        run: pnpm publish -r
